### ISSUE TITLE
VGGFace dataset

### ISSUE THREAD

**Issue by yeohhoo** [lingxiao-li/HAE#2]
Hello, I am very interested in your research and want to execute your program. However, when using the VGG Face dataset, I don’t know how to obtain it. I saw it from the link you gave. But the file format is .npy or .zip. I don't know how to use it. If you have a format  with ".jpg"  , can you share it. Or tell me how I can get it. Thank you so much!

**Comment by lingxiao-li** [comment]
Thanks for your interest. You can download the dataset using BaiduNetdisk using the following link: [https://pan.baidu.com/s/1YNipFVwrFA16Nl0D8FqSHg](https://pan.baidu.com/s/1YNipFVwrFA16Nl0D8FqSHg) password: ni24

**Comment by yeohhoo** [comment]
I am so excited about your sharing. Thank you very much！

**Comment by yeohhoo** [comment]
I am sorry to bother you again. However, I cannot find the Animal Face dataset ordered by class on any public website.  Could I ask you to share a copy of the Animal Face dataset you used in your article, please? Thanks!
