### ISSUE TITLE
Code error when using pre-trained model for inferrence

### ISSUE THREAD

**Issue by ZYBOBO** [lingxiao-li/HAE#3]
First, thanks for providing the source code for comparison!
However, when I run the inference.py with the pre-trained models and instructions you provided, the code does not run successfully. I need the generated images by HAE for comparative experiments,  could you provide clearer instructions for the inference? If I reproduce your results successfully, I will cite your paper in my work.

**Comment by lingxiao-li** [comment]
Could you show me the error message when you run inference.py? Second, if you want to get the newly generated images, you can use Visualization/[Interpolation & Perturbation.ipynb](https://github.com/lingxiao-li/HAE/blob/main/Visualization/Interpolation%20%26%20Perturbation.ipynb) to reproduce the results, inference.py only reconstructs the images.

**Comment by ZYBOBO** [comment]
Thanks for your reply. I misunderstood the purpose of the inference.py. I will use Visualization/[Interpolation & Perturbation.ipynb](https://github.com/lingxiao-li/HAE/blob/main/Visualization/Interpolation%20%26%20Perturbation.ipynb) to reproduce the results. 
 Thanks again for your kind help.
