### ISSUE TITLE
the discriminator of stylegan2

### ISSUE THREAD

**Issue by yeohhoo** [lingxiao-li/HAE#4]
Thank you for your iinteresting work! I have recently been studying and trying to understand your work. I saw the pre-trained weights of psp on three datasets in the Google Driver you provided, but I did not find the pre-trained weights of the discriminator of stylegan2. Could you please provide them to me? I am very grateful to you.

**Comment by lingxiao-li** [comment]
Sorry, I do not have the checkpoint for the discriminator of styleGAN2. I downloaded the pre-trained PSP directly from https://github.com/UniBester/AGE, maybe you can ask the author of AGE to check whether they have it. Thanks.

**Comment by yeohhoo** [comment]
OK, thanks for your reply, I will.
