### ISSUE TITLE
 Animal Face dataset 

### ISSUE THREAD

**Issue by yeohhoo** [lingxiao-li/HAE#5]
I am sorry to bother you again. However, I cannot find the Animal Face dataset ordered by class on any public website.  Could I ask you to share a copy of the Animal Face dataset you used in your article, please? Thanks!

**Comment by lingxiao-li** [comment]
You can download the dataset via this link: 通过网盘分享的文件：https://pan.baidu.com/s/15nAQr3WxFppot8br47L6Pg?pwd=ptta
